# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KxMenu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KxMenu

  target 'KxMenuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KxMenuUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'KxMenu'
end
