# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '界面悬浮效果' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 界面悬浮效果

  target '界面悬浮效果Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '界面悬浮效果UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SnapKit'
end
