# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '开发' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 开发

  target '开发Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '开发UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'MBProgressHUD'
pod 'Reachability'
end
