# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Masonry使用' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Masonry使用

  target 'Masonry使用Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Masonry使用UITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'Masonry'
end
